### ISSUE TITLE
DNS Server No Longer Works

### ISSUE THREAD

**Issue by shMaTT8DeDC68LjMk14bKcqY3L** [khalahan/nmcontrol#1]
I'm sure you already know, but the DNS server functionality no longer works.

I have hacked together some code to get simple Ipv4 address resolution working using the latest code, but it is a total mess.

Wondering when you are planning to get the DNS server working again? It doesn't seem too difficult just some decisions around which function should be doing the resolution...

**Comment by uVAdN2vUw2aMENSu19cY7ic24Gvp7Fd** [comment]
I made a pull request for this one

**Comment by khalahan** [comment]
The DNS server may be broken since commits after the 0.8 release due to a lot of changes in the pluginNamespaceDomain.

I've merged your commits in the master.
Thanks for fixing it :)
